### ISSUE TITLE
Regulator: Exploring zero-export compatibility

### ISSUE THREAD

**Issue by stealth-ultd** [jandrassy/Regulator#1]
Hi Juray,

Great to come across this well-documented DIY energy diverter. I am looking at a comparable setup for a Fronius Galvo, with the difference that in this case the utility company does not allow any power-to-grid (=zero export). This is implemented with a Fronius smartmeter (at feed-in point, modbus RTU) and with activation of Dynamic Power Reduction in the inverter DNO Editor settings ("Max. grid feed-in power: = -0.5%"). This last setting may look odd at first, but guarantees that there is always a minimum consumption taking place to avoid any export. 

What I would like to achieve is that surplus power can get diverter to a small supplementary heater (1.5 kW) while maintaining export limiting. Now I am not sure how the Regulator interacts with such a zero-export setting in the Fronius inverter.

Two initial questions about this: (1) Is there any reason to assume that the Regulator would not be compatible with zero-export, and (2) is it in any way necessary or helpful to have the secondary Fronius smartmeter (like you installed in 2019/5) for this setup?

**Comment by jandrassy** [comment]
Hi. my project reads the Smart Meter. You would need to know how much power would be available without dynamic reduction. I think this information is not available anywhere. I think the MPPT configures the parameters, but there is no way to know how much would be produced with optimal parameters.

**Comment by jandrassy** [comment]
Maybe one way would be to ramp the consumption until Smart Meter reports that power is drawn from grid and then regulate to some small power draw.

**Comment by stealth-ultd** [comment]
Hi,
Thanks for the explanation. Interesting. It is reverse-engineering the workings of the Fronius Ohmpilot, in some way (the last works with zero-export since a recent firmware update of the data-manager, Software Version: V3.13.3-2). Curious if it follows the same approach of ramping up consumption, or if it interacts on a deeper level with the MPPT. Not sure if the Fronius SunSpec implementation gives away any clue on how this is done.

**Comment by jandrassy** [comment]
the SunSpec has status I_STATUS_THROTTLED. So until status is THROTTLED the consumption can ramp up. (or until max power is reached).
I would love to try it, but I am very busy with work now and the season of surplus is at the end in some weeks this year. So it will have to wait until Spring.

**Comment by stealth-ultd** [comment]
Although little detail is available on how the Ohmpilot exactly manages this, others report indeed a gradual ramping up of the power. Will explore this a bit further.
I am using it for complementary heating in the colder seasons, so the most relevant time (autumn, spring) is starting in a bit, when solar is still abundent but not completely used. In any case, I will now first start gathering the hardware required!

**Comment by jandrassy** [comment]
I didn't commit the code yet, but I replaced the Kemo modules with a Triac dimmer
https://robotdyn.com/ac-light-dimmer-module-1-channel-3-3v-5v-logic-ac-50-60hz-220v-110v.html
and the MCU handles the zero-crossing to phase-cutting with the Triac

**Comment by stealth-ultd** [comment]
Good to know, that makes things more simple. Does the Triac dimmer also eliminate the need for the Grove MOSFET module?

**Comment by jandrassy** [comment]
I already forgot that I used a MOSFET :-). I had the MOSFET only for 3.3 V boards (Wemos D1 R2 and M0). I didn't use it for AVR boards (Uno (WiFi) and Mega). Same applies for the I2C ADC.

to other hardware:

I had the I2C ADC for esp8266 (D1 R2) because it has only one and not very good analog port.
And with SAMD (M0) I didn't solve analogRead from the CT yet. The readings have some inertia. Plotted waves are asymmetric.

The Chinese relays don't last long. One, maybe two seasons. First they start to generate strong EMI which disturbs the Ethernet chip. Finally they stop switching. I plan to replace them with DIN rail relays with 230 V coil switched by the new Grove 230 V sold state relay modules.

I have an ATmega1284 board ready to use with Regulator but no time to put it in and test. I want to test the Triac control with AVR and revisit AVR analogRead. If the AVR doesn't turn out fantastic, then I will return to SAMD, but not to M0. I plan to buy the Arduino MKR Connector Carrier (Grove compatible) and MKR ETH shield for my MKR Zero. The configuration will better fit in the box and I hope it will be less sensitive to EMI with ground lines not going over the Eth Shield like with Grove Base Shield.

**Comment by jandrassy** [comment]
don't miss the previous comment :-)

I use the double dimmer for larger cooler. For 2 kW the single dimmer overheated.  First I added a fan. It helped but it was noisy. For 1.5 kW it should be good.

I can't close the box now, because. the shields are high. But the SPI wires to external Ethernet modules catch EMI from relays and it disturbs Ethernet chip and SD card.

![20190910_213259](https://user-images.githubusercontent.com/10706773/64644832-d5ec2180-d413-11e9-9740-3e2097badfeb.jpg)

**Comment by stealth-ultd** [comment]
That’s quite some modification going on in the background! Some thoughts before updating my component list :-)

The Chinese relays failing with lots of EMI likely points to sparking (bad contact). Apart from maybe suspicious component quality, one other source could be low activation voltage / current. The relays have an operating voltage of 4.75V~5.25V at 185mA . Especially when driven with 3.3V boards the combination of voltage / current available may just be not enough to properly trigger them (two of them: 0.4 A, which is quite a draw on those boards). That had made me think of using a "30A 1-Channel Relay Module with Optocoupler H/L Level Triger”. They can be independently powered with 9 or 12 V directly from the main power supply, while the signal (3.3 or 5V) comes from the MCU. Have you maybe thought of that option too before considering the solid state relays?

I am curious how well the CT reading works at higher powers, as the CT is “only" rated at 5A and has to operate at nearly 9A (2kW). It may experience saturation of the (ferrite) core and give a distorted waveform (harmonics). I don’t know if this explains some of the CT readings at the SAMD (M0) or that something else is at play there.

EMI may in general be a plague due to all the switching electronics (SMPS, PMW, …), so I was planning to add (larger) ferrite cores to filter EMI on all the cabling getting in and out (power, ethernet, etc.) and where necessary on the internal connections.

Also I have been wondering about the connection with the inverter – I was looking at ModBus RTU, rather than TCP. We have the Fronius smartmeter already connected over RTU and extending it to the regulator may be easy – and less prone to possible communications errors from all the other “talk” that is going on over TCP (router, laptops, etc.) or EMI. I found some small Modbus RTU controllers that may do the trick.

And I am still in doubt about the Robotdyn triac dimmer versus the Kemo 150/028N module. The fist being inexpensive, but maybe underrated (or: overstated!) with risk of blowing out / the second supposedly more solid but significantly larger and expensive. Not sure where to go here. (In any case, both benefit from EMI chokes, the 028N has an extended filter design in the manual included.)

The Arduino MKR looks like a good choice indeed, especially with its small form-factor. Nice suggestion, I consider jumping on that one immediately. I guess this has no immediate effects on the sketch, as that all should be compatible?

**Comment by jandrassy** [comment]
all boards I used in the project have a regulator and the power source is good. The planed MKR Connector Carrier would be even better. The Grove modules get only the signal from MCU, the power is from regulator in my setup.

the Grove CT is to 10 A. the datasheet has wrong calculation of ratio. For SAMD I measured only half of the current (see the dashed line in 'schematics').

With Smart Meter you can't use Modbus RTU because the inverter is Modbus RTU master.

In some moment of understanding I realized how unnecessary complicated is to go over the Kemo modules. First PWM to digital pot and then the regulation module controlde by the pot. The direct control of Triac works fantastic. It is very exact compared to commanding the modules by PWM. The formula to calculate the period for available power is simpler and cleaner. I installed the Triac in Jun so it worked all Summer.

Yes the MKR Zero is compatible with the Regulator sketch.

**Comment by jandrassy** [comment]
I made the commit of the code with dimmer module support. and some development utils sources

**Comment by stealth-ultd** [comment]
This is very helpful - thanks.

You convinced me about direct control via the Robotdyn triac, will surely include that ;-)

Regarding Modbus RTU – I had missed that. Indeed, no other option than TCP.

As for the relays, I consider to go solid state option completely, for instance with DIN-rail mounted TRA23D25L (they include heatsink). We’ll see how this works.

Hardware list now getting complete.

**Comment by jandrassy** [comment]
I think the TRA23D25L are based on a Triac.

a 230 V SSR could be used instead of the Triac module for phase cutting.

**Comment by jandrassy** [comment]
Before the Kemo modules I had power regulation box controlled by PWM signal. It was based on a Triac and some MCU. I didn't understand phase cutting then. The cooler in the box was heating-up to very hot (now I know it is normal) and it didn't get to full power. Full on it enabled 1950 W but with direct connection the heater consumed 2050 W. So I implemented a 'bypass' relay for full power.
The Kemo module didn't heat-up, it was only warm, but it too doesn't alow full power.

Now with direct control of the Triac I can regulate from 10 W to 2050 W, but the cooler is very hot at higher regulated power  and on full power too.

The Triac based SSR you linked will get hot too. And this SSR can be used to regulate the power with phase cutting, but the there is no point to use a 'bypass'. The specs table says they have 'zero-crossing'. I wonder if they turn of on zero-crossing like a plain Triac. If not, then the MCU would need to hold the pin HIGH instead of sending a short pulse to Triac.

My Triac journey started here https://arduino.stackexchange.com/questions/63631/fan-regulator-control-from-arduino/63674#63674

**Comment by stealth-ultd** [comment]
The TRA23D25L is based on a Triac. What attracted me is that it is compact, DIN-rail mounted and has a heatsink attached. Reading more about SSR’s during these last days show that they indeed may run hot like you mention – maybe more than I hoped for. We’ll see.

This specific SSR has a zero-crossing detection circuit. So it will turn on only at the ZC point. As long as the input is HIGH, the gate will remain triggered, and when the input goes LOW, it will switch off at ZC. To keep it on, the pin needs to be held HIGH.

From what I now understand, this is not the best type of SSR for phase cutting. A ‘random firing’ SSR would be better here, because it can be triggered at any desired point of the wave (but will wait for ZC to switch 'neatly' off). Among the many, this article (https://hackaday.com/2017/09/26/an-introduction-to-solid-state-relays/) was helpful summing it up.

Probably for power regulation the Robotdyn (with direct control of the Triac) is the most elegant solution (even if running quite hot). And if the SSR keeps cooler, it may be an alternative for the bypass. In any case, I plan to use it for space heating ;-)

**Comment by jandrassy** [comment]
I checked the schematics of the Grove Electricity Sensor (the CT module) and I wonder that it didn't destroy any analog pin with -5 V. Uno WiFi had it wired more than a year. I wired it to Wemos, M0, MKR. The Grove I2C ADC has some level shifting circuit on input which maybe protects it.
The schematics of the CT module was not available before and the description is misleading.

I ordered the new Grove AC sensor (<5A ACS70331). With it the MKR Grove Base and a new relay again. I replaced the bypass relay some weeks ago, now the main relay causes W5500 reset at AC disconnection while only the 40 W circulation pump is running.

**Comment by jandrassy** [comment]
I could test the new AC sensor today. It reads nice sine wave with AVR and with SAMD. The middle value is around 1,5 V so it is good for a 3.3 V MCU. 

I tested it with the MKR connector base too, but the shield has signal level shifting. For analog pins there is a voltage divider and a capacitor. The capacitor smoothed the AC wave to no wave.

**Comment by stealth-ultd** [comment]
Would it work if you connect it directly to an analog pin on the MKR Zero, or otherwise through the I2C ADC board to the MKR connector carrier?

**Comment by jandrassy** [comment]
> Would it work if you connect it directly to an analog pin on the MKR Zero, or otherwise through the I2C ADC board to the MKR connector carrier?

yes I tested it then directly connected and it works perfect with 3.3 V Vcc and ADC.

**Comment by stealth-ultd** [comment]
If the sensor proves to work when directly connected to an analog pin on the MKR Zero, the capacitor on the shield could be taken out (soldering it off). It's a bit fiddly but possible.

When your load hits 2kW, what does the sensor read? The specs state that it can handle 10A, but maxes out measuring at 5A , which should be somewhere around 1.2kW. Does it still provide reliable readings beyond that?

**Comment by jandrassy** [comment]
analogRead is close to zero at - 5 A. at zero crossing analogRead reads around 450 on MKR.

Yesterday I tested only with a 40 W bulb and with a 1 kW portable heater. In the Regulator box I will split the AC line and measure only half of the current. See the updated schematics in README

**Comment by jandrassy** [comment]
update

the EMI problem with main relay was not solved with a new relay, but with swap to pin 3. 

the Grove AC sensor is usable. less current goes over it with the split wire the I expected, so the read values are only +-100, but the `readElSens` function returns good values. (I multiple the float with 1000 for the return value.) and the `elsensPower` calculation with modified coefficients gives accurate values.

If we have some sunny day at weekend I will try a 30 A hall effect AC sensor without AC wire split to compare with the Grove AC sensor readings.

**Comment by jandrassy** [comment]
Yes, the current sensor I still plan to test is ACS712 30 A. The sensor is 5 V and has the middle output value at 2.5 V. So for a 3.3 V board the measured current can generate only up to 3.3 V. For your 1500 W the 20 A version should be good and for my 2000 W the 30 A version should not go over 3.3 V at 9 A.

and about DIN rail mount: did you see this? https://industruino.com/page/products

**Comment by stealth-ultd** [comment]
Had not seen those modules before. If the Regulator goes into series production it may be a good option ;-)

These current sensors should work indeed. And with the MKR Connector Carrier (& DAC) it could use the entire range of the sensor, as far as I can see. "All the I/Os are supplied at 5V and the carrier provides the proper 5V to 3.3V level shifting.".

I am considering to extrapolate the "surplus" using a separate mini solar panel (with load resister & DAC) next to the main PV panels, to measure the amount of irradiation (or alternatively, % of output). With that info the surplus could be approximated. Might be worth giving a try...

**Comment by jandrassy** [comment]
All the analog connectors of the Carrier have voltage divider and a capacitor and the capacitor smooths the AC wave away. I don't know what for is the capacitor and how do this connectors work as output.

an LDR could measure the sun light too (protected by sun glasses :-) )

**Comment by jandrassy** [comment]
so finally I use the 30 A ACS712. the splitted wire for the 5 V sensor distorts the measurement.

the new commit with the code modifications for ACS712 contains Calc sheets I use for coefficients of formulas and readme.md with comments. the sheets have example data

**Comment by jandrassy** [comment]
@stealth-ultd, did you build it? Or you bought the Ohmpilot?

**Comment by stealth-ultd** [comment]
Sorry for the delayed response. It is here on the bench - no Ohmpilot in sight! But before connecting (and deciding on the necessary changes to be implemented in the code) I am waiting for a change in the inverter setup. Likely, we will change from 1-phase to 3-phase setup and have export enabled. Need permission from network regulator for this. Just everything is slowed down now because of lockdown. If we get permission, it will stay closer to your setup.

**Comment by stealth-ultd** [comment]
It has been a while since I have been coding, so taking this Regulator for a new start has been “interesting”. That said, the code is laid out elegantly and pretty well-annotated, so it is advancing good. The Regulator is since a few days feeding a storage heater (6.4 kWh thermal battery) from excess PV supplemented by nighttime tariff “imported” electricity.

We are still waiting for permission for the Distributive Grid Operator (takes months, unfortunately) to connect a three-phase inverter and allow export. So, for now, our regulator implementation remains somewhat improvised and regulated through MQTT commands from Node-Red rather than ModBus. Not running a pump meant I could recycle its alarm code for MQTT client connection (alike the network alarm function). I opted for a somewhat lower “beep” tone for the beeper, though ;-) Piece by piece, it is coming together – and yes, the modularity of the code is very helpful in this.

Yesterday got ElSens working (with ACS712 20A through MKR Carrier, with A0 resistor unsoldered), however, I am now a bit puzzled with the calibration of the readings.

- In principle, I am using a “perfect” 0.8kW resistive load, so the Power factor should be nearly 1. What settings should be used for PF_ANGLE_INTERVAL and PF_ANGLE_SHIFT in this case (and how did you figure the values for your system, where I guess the main 2kW heating element is also nearly “perfect” resistive apart from the 40W pump)?
- There is a scaling factor ELSENS_VALUE_COEF = 1.86 – is this number based on reverse-engineering the value to get a matching elsensPower value, or else?

**Comment by jandrassy** [comment]
I am glad my project helps.

I write about ElSens here https://github.com/jandrassy/Regulator/tree/master/util/Calc#elsenspower

it is not a 'true' power factor like when the AC voltage and current are shifted. this 'power factor' is from cutting away part of the current wave. 

I expolored the EMI from relay. I switch the relays at zero crossing, but It turns out that the bypass relay at full load takes 10 milliseconds until it disconnects so it disconnects at next zero crossing. The main relay which at switch off has only 40 W of the circulation pump, switches off after 5 milliseconds so exactly at voltage peek which creates EMI.

**Comment by stealth-ultd** [comment]
Thanks for the quick response! I'll start with manually adding some samples to RegulatorDev.ods and see where we get with calibrating Elsens. Right now I am using still a different thyristor library (dimmable_light_linearized.h), plan to switch to TriacLib in the next days.

I have been using a solid-state relay with ESP8622 on which the code was running before, but the MKR Zero has a slightly lower output voltage on the pin and it won't switch the SSR for bypass mode (yes indeed, that dimmer gets hot, even with an extra heatsink attached!). Thinking about driving the SSR from a mosfet. When I get it all sorted I will hook on the oscilloscope and check how clean the output stays. But first things first ...

**Comment by stealth-ultd** [comment]
The Calc part is definitively helpful. I've now also implemented the TriacLib, calibrated power to period with dimmer-dev.ods. Manually calibrating with RegulatorDev.ods works like a charm.

**Comment by stealth-ultd** [comment]
A quick question as I am about to implement the Modbus functionality. A look at the code tells that the inverter needs to be in slave mode ("Inverter control via Modbus") and that you write to the interface (modbus.write). Is this required to read out the data? I have no battery functionality in the Galvo (and upcoming Symo) so I am not intentding to change the state of the inverter through the Regulator.

**Comment by jandrassy** [comment]
Regulator uses Modbus TCP. Modbus TCP has server and client, not master and slave. The Symo is server and Regulator is a client. 
Modbus RTU can't be used because there Data Manager is master and Smart Meter and BMS are slaves. Ohmpilot is slave too and the Data Manager firmware as master sends data to Ohmpilot as slave. There can be only one master in Modbus RTU.

**Comment by stealth-ultd** [comment]
I am aware of this, I guess my question was not clear.
In the web admin of the inverterou set to control the inverter via Modbus. Why is that "control" necessary? OR: is it still necessary if I just want to read (request) data from the inverter and smart meter via Modbus TCP for the Regulator, without any intention to influence the actual state of the inverter. It is that "control" bit that confuses me here.

**Comment by jandrassy** [comment]
sorry. yes 'control' is to allow for write operations. I use the modbusWriteSingle() function in Modbus.ino only from BattSett.ino

**Comment by stealth-ultd** [comment]
Clear, thanks :-)

BTW: Is the symo service password crucial for any of this communication? I see it used in SusCalib.ino but maybe that's not relevant for my setup (no battery).

**Comment by jandrassy** [comment]
SusCalib uses JSON API (an undocumented request used by the web GUI).
modbus tcp doesn't require a password
